-- ============================================================
-- SISTEMA RAAS - Script de Criação do Banco de Dados
-- Execute este script no SQL Editor do Supabase
-- ============================================================

-- ============================================================
-- 1. PROFISSIONAIS
-- ============================================================
CREATE TABLE IF NOT EXISTS profissionais (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  cns VARCHAR(15) NOT NULL,
  cbo VARCHAR(10) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- ============================================================
-- 2. PACIENTES
-- ============================================================
CREATE TABLE IF NOT EXISTS pacientes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  cartao_sus VARCHAR(20) NOT NULL UNIQUE,
  cpf VARCHAR(14),
  sexo CHAR(1) CHECK (sexo IN ('M', 'F')),
  data_nascimento VARCHAR(10) NOT NULL,
  nome_mae TEXT NOT NULL,
  endereco TEXT,
  telefone VARCHAR(20),
  data_admissao VARCHAR(10),
  cid_principal VARCHAR(10),
  cid_associado VARCHAR(10),
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- ============================================================
-- 3. PROCEDIMENTOS (Códigos de Ação)
-- ============================================================
CREATE TABLE IF NOT EXISTS procedimentos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(20) NOT NULL UNIQUE,
  observacao TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- ============================================================
-- 4. FICHAS MENSAIS (Uma por paciente por mês)
-- ============================================================
CREATE TABLE IF NOT EXISTS fichas_mensais (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  paciente_id BIGINT NOT NULL REFERENCES pacientes(id) ON DELETE CASCADE,
  mes_atendimento VARCHAR(7) NOT NULL, -- Formato: '2026-08'
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  UNIQUE (paciente_id, mes_atendimento)
);

-- ============================================================
-- 5. AÇÕES REALIZADAS (Procedimentos de cada ficha mensal)
-- ============================================================
CREATE TABLE IF NOT EXISTS acoes_realizadas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ficha_id BIGINT NOT NULL REFERENCES fichas_mensais(id) ON DELETE CASCADE,
  procedimento_codigo VARCHAR(20) NOT NULL,
  quantidade INT DEFAULT 1 CHECK (quantidade > 0),
  data_realizacao VARCHAR(10) NOT NULL,
  profissional_id BIGINT REFERENCES profissionais(id),
  cbo VARCHAR(10) NOT NULL,
  cns VARCHAR(15) NOT NULL,
  local_acao VARCHAR(20) CHECK (local_acao IN ('CAPS', 'Território')),
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- ============================================================
-- HABILITAR ROW LEVEL SECURITY (RLS) - Boa prática Supabase
-- ============================================================
ALTER TABLE profissionais ENABLE ROW LEVEL SECURITY;
ALTER TABLE pacientes ENABLE ROW LEVEL SECURITY;
ALTER TABLE procedimentos ENABLE ROW LEVEL SECURITY;
ALTER TABLE fichas_mensais ENABLE ROW LEVEL SECURITY;
ALTER TABLE acoes_realizadas ENABLE ROW LEVEL SECURITY;

-- Policies: permitir tudo para usuários anônimos (ajuste quando tiver autenticação)
CREATE POLICY "allow_all_profissionais" ON profissionais FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "allow_all_pacientes" ON pacientes FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "allow_all_procedimentos" ON procedimentos FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "allow_all_fichas" ON fichas_mensais FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "allow_all_acoes" ON acoes_realizadas FOR ALL USING (true) WITH CHECK (true);

-- ============================================================
-- DADOS DE EXEMPLO (opcional - remova se não quiser)
-- ============================================================
INSERT INTO profissionais (nome, cns, cbo) VALUES
  ('Dr. João Silva', '123456789012345', '225125'),
  ('Dra. Ana Costa (Psicóloga)', '987654321054321', '251510')
ON CONFLICT DO NOTHING;

INSERT INTO procedimentos (codigo, observacao) VALUES
  ('0301010072', 'Consulta médica em atenção especializada'),
  ('0301010137', 'Atendimento individual em atenção especializada'),
  ('0301010048', 'Atendimento em grupo em atenção especializada')
ON CONFLICT DO NOTHING;
