-- ============================================================
-- SISTEMA RAAS - Script de Criação do Banco de Dados
-- Pode ser executado múltiplas vezes com total segurança
-- ============================================================

-- ============================================================
-- 1. PROFISSIONAIS
-- ============================================================
CREATE TABLE IF NOT EXISTS profissionais (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  cns VARCHAR(15) NOT NULL,
  cbo VARCHAR(10) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- ============================================================
-- 2. PACIENTES
-- ============================================================
CREATE TABLE IF NOT EXISTS pacientes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  cartao_sus VARCHAR(20) NOT NULL UNIQUE,
  cpf VARCHAR(14),
  sexo CHAR(1) CHECK (sexo IN ('M', 'F')),
  data_nascimento VARCHAR(10) NOT NULL,
  nome_mae TEXT NOT NULL,
  endereco TEXT,
  telefone VARCHAR(20),
  data_admissao VARCHAR(10),
  cid_principal VARCHAR(10),
  cid_associado VARCHAR(10),
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- ============================================================
-- 3. PROCEDIMENTOS (Códigos de Ação)
-- ============================================================
CREATE TABLE IF NOT EXISTS procedimentos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(20) NOT NULL UNIQUE,
  observacao TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- ============================================================
-- 4. FICHAS MENSAIS (Uma por paciente por mês)
-- ============================================================
CREATE TABLE IF NOT EXISTS fichas_mensais (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  paciente_id BIGINT NOT NULL REFERENCES pacientes(id) ON DELETE CASCADE,
  mes_atendimento VARCHAR(7) NOT NULL, -- Formato: '2026-08'
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  UNIQUE (paciente_id, mes_atendimento)
);

-- ============================================================
-- 5. AÇÕES REALIZADAS (Procedimentos de cada ficha mensal)
-- ============================================================
CREATE TABLE IF NOT EXISTS acoes_realizadas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ficha_id BIGINT NOT NULL REFERENCES fichas_mensais(id) ON DELETE CASCADE,
  codigo VARCHAR(20) NOT NULL,
  quantidade INT DEFAULT 1 CHECK (quantidade > 0),
  data VARCHAR(10) NOT NULL,
  profissional_id BIGINT REFERENCES profissionais(id),
  cbo VARCHAR(10) NOT NULL,
  cns VARCHAR(15) NOT NULL,
  local VARCHAR(20) CHECK (local IN ('CAPS', 'Território')),
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Compatibilidade se a tabela já existia com nomes antigos de colunas
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='acoes_realizadas' AND column_name='procedimento_codigo')
     AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='acoes_realizadas' AND column_name='codigo') THEN
    ALTER TABLE acoes_realizadas RENAME COLUMN procedimento_codigo TO codigo;
  END IF;

  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='acoes_realizadas' AND column_name='data_realizacao')
     AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='acoes_realizadas' AND column_name='data') THEN
    ALTER TABLE acoes_realizadas RENAME COLUMN data_realizacao TO data;
  END IF;

  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='acoes_realizadas' AND column_name='local_acao')
     AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='acoes_realizadas' AND column_name='local') THEN
    ALTER TABLE acoes_realizadas RENAME COLUMN local_acao TO local;
  END IF;
END $$;

-- ============================================================
-- 6. KEEPALIVE PINGS (Alimentada pelo GitHub Actions para manter ativo)
-- ============================================================
CREATE TABLE IF NOT EXISTS keepalive_pings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  origem VARCHAR(50) DEFAULT 'github_actions',
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- ============================================================
-- CONCEDER PERMISSÕES (GRANT) ÀS ROLES DO SUPABASE (anon, authenticated, service_role)
-- ============================================================
GRANT ALL ON TABLE public.profissionais TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.pacientes TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.procedimentos TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.fichas_mensais TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.acoes_realizadas TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.keepalive_pings TO anon, authenticated, service_role;

GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;

-- ============================================================
-- HABILITAR ROW LEVEL SECURITY (RLS) - Permissões de Acesso
-- ============================================================
ALTER TABLE profissionais ENABLE ROW LEVEL SECURITY;
ALTER TABLE pacientes ENABLE ROW LEVEL SECURITY;
ALTER TABLE procedimentos ENABLE ROW LEVEL SECURITY;
ALTER TABLE fichas_mensais ENABLE ROW LEVEL SECURITY;
ALTER TABLE acoes_realizadas ENABLE ROW LEVEL SECURITY;
ALTER TABLE keepalive_pings ENABLE ROW LEVEL SECURITY;

-- Limpa policies existentes para evitar erro de duplicidade e recria
DROP POLICY IF EXISTS "allow_all_profissionais" ON profissionais;
CREATE POLICY "allow_all_profissionais" ON profissionais FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "allow_all_pacientes" ON pacientes;
CREATE POLICY "allow_all_pacientes" ON pacientes FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "allow_all_procedimentos" ON procedimentos;
CREATE POLICY "allow_all_procedimentos" ON procedimentos FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "allow_all_fichas" ON fichas_mensais;
CREATE POLICY "allow_all_fichas" ON fichas_mensais FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "allow_all_acoes" ON acoes_realizadas;
CREATE POLICY "allow_all_acoes" ON acoes_realizadas FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "allow_all_keepalive" ON keepalive_pings;
CREATE POLICY "allow_all_keepalive" ON keepalive_pings FOR ALL USING (true) WITH CHECK (true);

-- ============================================================
-- DADOS INICIAIS DE EXEMPLO
-- ============================================================
INSERT INTO profissionais (nome, cns, cbo) VALUES
  ('Dr. João Silva', '123456789012345', '225125'),
  ('Dra. Ana Costa (Psicóloga)', '987654321054321', '251510')
ON CONFLICT DO NOTHING;

INSERT INTO procedimentos (codigo, observacao) VALUES
  ('0301010072', 'Consulta médica em atenção especializada'),
  ('0301010137', 'Atendimento individual em atenção especializada'),
  ('0301010048', 'Atendimento em grupo em atenção especializada')
ON CONFLICT DO NOTHING;
