-- ============================================================
-- SISTEMA RAAS - Script de Criação do Banco de Dados
-- Pode ser executado múltiplas vezes com total segurança
-- ============================================================

-- ============================================================
-- 1. PROFISSIONAIS
-- ============================================================
CREATE TABLE IF NOT EXISTS profissionais (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  cns TEXT NOT NULL,
  cbo TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- ============================================================
-- 2. PACIENTES
-- ============================================================
CREATE TABLE IF NOT EXISTS pacientes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  cartao_sus TEXT NOT NULL UNIQUE,
  cpf TEXT,
  sexo TEXT,
  data_nascimento TEXT NOT NULL,
  nome_mae TEXT NOT NULL,
  endereco TEXT,
  telefone TEXT,
  data_admissao TEXT,
  cid_principal TEXT,
  cid_associado TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- ============================================================
-- 3. PROCEDIMENTOS (Códigos de Ação)
-- ============================================================
CREATE TABLE IF NOT EXISTS procedimentos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo TEXT NOT NULL UNIQUE,
  observacao TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- ============================================================
-- 4. FICHAS MENSAIS (Uma por paciente por mês)
-- ============================================================
CREATE TABLE IF NOT EXISTS fichas_mensais (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  paciente_id BIGINT NOT NULL REFERENCES pacientes(id) ON DELETE CASCADE,
  mes_atendimento TEXT NOT NULL, -- Formato: '2026-08'
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  UNIQUE (paciente_id, mes_atendimento)
);

-- ============================================================
-- 5. AÇÕES REALIZADAS (Procedimentos de cada ficha mensal)
-- ============================================================
CREATE TABLE IF NOT EXISTS acoes_realizadas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ficha_id BIGINT NOT NULL REFERENCES fichas_mensais(id) ON DELETE CASCADE,
  codigo TEXT NOT NULL,
  quantidade INT DEFAULT 1 CHECK (quantidade > 0),
  data TEXT NOT NULL,
  profissional_id BIGINT REFERENCES profissionais(id),
  cbo TEXT NOT NULL,
  cns TEXT NOT NULL,
  local TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Compatibilidade e expansão de tipos para tabelas que já existiam
DO $$
BEGIN
  -- Ajustar nomes de colunas antigas se existirem
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='acoes_realizadas' AND column_name='procedimento_codigo')
     AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='acoes_realizadas' AND column_name='codigo') THEN
    ALTER TABLE acoes_realizadas RENAME COLUMN procedimento_codigo TO codigo;
  END IF;

  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='acoes_realizadas' AND column_name='data_realizacao')
     AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='acoes_realizadas' AND column_name='data') THEN
    ALTER TABLE acoes_realizadas RENAME COLUMN data_realizacao TO data;
  END IF;

  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='acoes_realizadas' AND column_name='local_acao')
     AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='acoes_realizadas' AND column_name='local') THEN
    ALTER TABLE acoes_realizadas RENAME COLUMN local_acao TO local;
  END IF;

  -- Expandir tipos VARCHAR limitados para TEXT (evita erro "value too long")
  ALTER TABLE public.profissionais ALTER COLUMN cbo TYPE TEXT;
  ALTER TABLE public.profissionais ALTER COLUMN cns TYPE TEXT;
  ALTER TABLE public.pacientes ALTER COLUMN cartao_sus TYPE TEXT;
  ALTER TABLE public.pacientes ALTER COLUMN cpf TYPE TEXT;
  ALTER TABLE public.pacientes ALTER COLUMN sexo TYPE TEXT;
  ALTER TABLE public.pacientes ALTER COLUMN data_nascimento TYPE TEXT;
  ALTER TABLE public.pacientes ALTER COLUMN telefone TYPE TEXT;
  ALTER TABLE public.pacientes ALTER COLUMN data_admissao TYPE TEXT;
  ALTER TABLE public.pacientes ALTER COLUMN cid_principal TYPE TEXT;
  ALTER TABLE public.pacientes ALTER COLUMN cid_associado TYPE TEXT;
  ALTER TABLE public.procedimentos ALTER COLUMN codigo TYPE TEXT;
  ALTER TABLE public.fichas_mensais ALTER COLUMN mes_atendimento TYPE TEXT;
  ALTER TABLE public.acoes_realizadas ALTER COLUMN codigo TYPE TEXT;
  ALTER TABLE public.acoes_realizadas ALTER COLUMN data TYPE TEXT;
  ALTER TABLE public.acoes_realizadas ALTER COLUMN cbo TYPE TEXT;
  ALTER TABLE public.acoes_realizadas ALTER COLUMN cns TYPE TEXT;
  ALTER TABLE public.acoes_realizadas ALTER COLUMN local TYPE TEXT;
END $$;

-- ============================================================
-- 6. KEEPALIVE PINGS (Alimentada pelo GitHub Actions para manter ativo)
-- ============================================================
CREATE TABLE IF NOT EXISTS keepalive_pings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  origem TEXT DEFAULT 'github_actions',
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- ============================================================
-- CONCEDER PERMISSÕES (GRANT) ÀS ROLES DO SUPABASE (anon, authenticated, service_role)
-- ============================================================
GRANT ALL ON TABLE public.profissionais TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.pacientes TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.procedimentos TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.fichas_mensais TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.acoes_realizadas TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.keepalive_pings TO anon, authenticated, service_role;

GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;

-- ============================================================
-- HABILITAR ROW LEVEL SECURITY (RLS) - Permissões de Acesso
-- ============================================================
ALTER TABLE profissionais ENABLE ROW LEVEL SECURITY;
ALTER TABLE pacientes ENABLE ROW LEVEL SECURITY;
ALTER TABLE procedimentos ENABLE ROW LEVEL SECURITY;
ALTER TABLE fichas_mensais ENABLE ROW LEVEL SECURITY;
ALTER TABLE acoes_realizadas ENABLE ROW LEVEL SECURITY;
ALTER TABLE keepalive_pings ENABLE ROW LEVEL SECURITY;

-- Limpa policies existentes para evitar erro de duplicidade e recria
DROP POLICY IF EXISTS "allow_all_profissionais" ON profissionais;
CREATE POLICY "allow_all_profissionais" ON profissionais FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "allow_all_pacientes" ON pacientes;
CREATE POLICY "allow_all_pacientes" ON pacientes FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "allow_all_procedimentos" ON procedimentos;
CREATE POLICY "allow_all_procedimentos" ON procedimentos FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "allow_all_fichas" ON fichas_mensais;
CREATE POLICY "allow_all_fichas" ON fichas_mensais FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "allow_all_acoes" ON acoes_realizadas;
CREATE POLICY "allow_all_acoes" ON acoes_realizadas FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "allow_all_keepalive" ON keepalive_pings;
CREATE POLICY "allow_all_keepalive" ON keepalive_pings FOR ALL USING (true) WITH CHECK (true);

-- ============================================================
-- DADOS INICIAIS DE EXEMPLO
-- ============================================================
INSERT INTO profissionais (nome, cns, cbo) VALUES
  ('Dr. João Silva', '123456789012345', '225125'),
  ('Dra. Ana Costa (Psicóloga)', '987654321054321', '251510')
ON CONFLICT DO NOTHING;

INSERT INTO procedimentos (codigo, observacao) VALUES
  ('0301010072', 'Consulta médica em atenção especializada'),
  ('0301010137', 'Atendimento individual em atenção especializada'),
  ('0301010048', 'Atendimento em grupo em atenção especializada')
ON CONFLICT DO NOTHING;
